name: Sync upstream/main to fork's main + backups (containers)

on:
  schedule:
    - cron: "0 0 * * *"   # täglich 00:00 UTC = 02:00 Berlin (Sommerzeit)
  workflow_dispatch: {}

permissions:
  contents: write

env:
  UPSTREAM: https://github.com/bitnami/containers.git
  RETENTION_DAYS: "60"
  BACKUP_PREFIX: "backup/main-"
  TZ: "Europe/Berlin"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout automation branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add remotes & fetch
        run: |
          git remote add upstream "$UPSTREAM" || true
          git fetch origin --prune
          git fetch upstream --prune --tags

      - name: "Guard: ensure upstream main exists"
        run: git ls-remote --exit-code --heads upstream main >/dev/null

      # Backup vor dem Sync (aus aktuellem Fork-main)
      - name: Create nightly backup branch from current main
        run: |
          set -e
          git fetch origin main:refs/remotes/origin/main
          BACKUP_BRANCH="${BACKUP_PREFIX}$(TZ=$TZ date +%F)"
          git branch -f "$BACKUP_BRANCH" refs/remotes/origin/main
          git push --force-with-lease origin "refs/heads/$BACKUP_BRANCH:refs/heads/$BACKUP_BRANCH"

      # Sync: Upstream → Fork main (ohne Workflow-Dateien)
      # Diese Lösung vermeidet das Permissions-Problem mit Workflow-Dateien
      - name: Update fork's main from upstream/main (excluding workflow files)
        run: |
          # Erstelle temporären Branch für den Sync
          set -e
          git fetch upstream main
          git checkout -b temp-sync-branch upstream/main
          
          # Hole aktuellen Stand von main
          git fetch origin main:refs/remotes/origin/main
          
          # Bewahre .github/workflows aus dem Fork
          echo "Bewahre Workflow-Dateien aus dem Fork"
          git checkout origin/main -- .github/workflows
          
          # Commit die Änderungen nur wenn es Änderungen gibt
          git add .github/workflows
          if ! git diff --staged --quiet; then
            git commit -m "Preserve workflow files from fork"
            echo "Workflow-Dateien wurden beibehalten"
          else
            echo "Keine Änderungen an Workflow-Dateien"
          fi
          
          # Push zum main branch
          echo "Aktualisiere main Branch"
          git push origin temp-sync-branch:main --force

      # Alte Backups entfernen
      - name: Prune backup branches older than RETENTION_DAYS
        run: |
          set -e
          CUTOFF="$(TZ=$TZ date -d "-${RETENTION_DAYS} days" +%F)"
          git ls-remote --heads origin "${BACKUP_PREFIX}*" \
            | awk '{print $2}' | sed 's#refs/heads/##' \
            | while read -r br; do
                DATE_PART="${br##${BACKUP_PREFIX}}"
                # Verwende date für einen korrekten Datumsvergleich
                if [[ $(date -d "$DATE_PART" +%s 2>/dev/null) -lt $(date -d "$CUTOFF" +%s 2>/dev/null) ]]; then
                  echo "Lösche alten Branch: $br (Datum: $DATE_PART, älter als Cutoff: $CUTOFF)"
                  git push origin --delete "$br"
                fi
              done

